import React,{useState} from "react";
import {createRoot} from "react-dom/client";
import {useAgent} from "agents/react";
import {useAgentChat} from "@cloudflare/ai-chat/react";
import "./styles.css";

function ChatPanel(){
  const agent=useAgent({agent:"CareerAgent"});
  const {messages,sendMessage,clearHistory,status}=useAgentChat({agent});
  const [input,setInput]=useState("");
  const submit=(e:React.FormEvent)=>{e.preventDefault();const text=input.trim();if(!text||status==="streaming")return;sendMessage({text});setInput("");};
  return <section className="panel"><div className="panel-head"><div><span className="eyebrow">LIVE AGENT</span><h2>Career Copilot</h2></div><button className="ghost" onClick={clearHistory}>Clear</button></div><div className="messages">{messages.length===0?<div className="empty"><div className="spark">✦</div><h3>Ask me about your next application.</h3><p>Try “What are my strongest Java backend skills?”</p></div>:messages.map(m=><div className={`message ${m.role}`} key={m.id}><div className="message-role">{m.role==="user"?"YOU":"COPILOT"}</div>{m.parts.map((p,i)=>p.type==="text"?<div className="message-text" key={i}>{p.text}</div>:null)}</div>)}</div><form className="composer" onSubmit={submit}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about your profile, projects or an application…"/><button disabled={status==="streaming"}>{status==="streaming"?"Thinking…":"Send"}</button></form></section>;
}
function ResultList({title,items=[]}:{title:string;items?:string[]}){return <div><h3>{title}</h3><ul>{items.map((x,i)=><li key={i}>{x}</li>)}</ul></div>}
function Analyzer(){
  const [job,setJob]=useState(""),[role,setRole]=useState(""),[company,setCompany]=useState(""),[result,setResult]=useState<any>(null),[loading,setLoading]=useState(false),[seeded,setSeeded]=useState(false);
  const seed=async()=>{await fetch("/api/seed",{method:"POST"});setSeeded(true)};
  const analyze=async()=>{if(!job.trim())return;setLoading(true);setResult(null);const start=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobDescription:job,targetRole:role,targetCompany:company})});const {id}=await start.json();for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,1200));const s=await (await fetch(`/api/workflow/${id}`)).json();if(s.status==="complete"){setResult(s.output);break}if(s.status==="errored"||s.status==="terminated"){setResult({error:s.error??"Workflow failed"});break}}setLoading(false)};
  return <section className="panel analyzer"><div className="panel-head"><div><span className="eyebrow">DURABLE WORKFLOW + RAG</span><h2>Job Fit Analyzer</h2></div><button className="secondary" onClick={seed}>{seeded?"Knowledge seeded ✓":"Seed demo knowledge"}</button></div><p className="subtle">Paste a job description. The workflow retrieves candidate evidence from Vectorize, asks Llama 3.3 to score fit, then creates an action plan.</p><div className="row"><input value={role} onChange={e=>setRole(e.target.value)} placeholder="Target role (optional)"/><input value={company} onChange={e=>setCompany(e.target.value)} placeholder="Company (optional)"/></div><textarea value={job} onChange={e=>setJob(e.target.value)} placeholder="Paste the job description here…" rows={8}/><button className="primary" onClick={analyze} disabled={loading||!job.trim()}>{loading?"Running durable workflow…":"Analyze role"}</button>{result?.analysis&&<div className="result"><div className="score"><strong>{result.analysis.matchScore??"—"}</strong><span>/100 fit</span></div><div className="result-grid"><ResultList title="Strengths" items={result.analysis.strengths}/><ResultList title="Gaps" items={result.analysis.gaps}/><ResultList title="Keywords" items={result.analysis.keywordsToEmphasize}/><ResultList title="Risks" items={result.analysis.risks}/></div><div className="plan"><h3>Action plan</h3><pre>{result.actionPlan}</pre></div></div>}{result?.error&&<div className="error">{result.error}</div>}</section>;
}
function App(){return <main><header className="hero"><div><span className="eyebrow">CLOUDFLARE AI ASSIGNMENT</span><h1>Career<span>Copilot</span></h1><p>An AI-powered job application assistant with persistent agent memory, semantic retrieval and durable workflows.</p></div><div className="architecture"><span>LLM</span><i>→</i><span>Agent</span><i>→</i><span>RAG</span><i>→</i><span>Workflow</span></div></header><div className="grid"><ChatPanel/><Analyzer/></div><footer>Workers AI · Agents SDK · Durable Objects · Vectorize · Workflows</footer></main>}
createRoot(document.getElementById("root")!).render(<App/>);
